[tool.poetry]
name = "hms-brain-activity"
version = "0.1.0"
description = "An attempt at a Kaggle competition for seizure detection."
authors = ["BlakeJC94 <blakejamescook@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.0"
torch = "^2.2.0"
lightning = "^2.2.0.post0"
torchaudio = "^2.2.0"
torchvision = "^0.17.0"
mne = "^1.6.1"
plotly = "^5.19.0"
pyarrow = "^15.0.0"
clearml = "^1.14.4"
torchmetrics = "^1.3.1"
matplotlib = "^3.8.3"


[tool.poetry.group.dev.dependencies]
ipython = "^8.21.0"
black = "^24.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
